### ISSUE TITLE
Installing the profile on Android 6 doesn't configure phase 2 authentication

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence-android-agent#2]
It also doesn't open the wifi menu afterwards and just tries to connect to it but since there is no credentials, it ends up failing

**Comment by tlaurion** [comment]
[This](http://www.programcreek.com/java-api-examples/index.php?source_dir=MDM-Android-Agent-master/src/com/wso2/mobile/mdm/api/WiFiConfig.java) seems to use reflection to properly set phase2. 

Else, since API level 18 (Android 4.3) there is an [API](https://developer.android.com/reference/android/net/wifi/WifiEnterpriseConfig.html) that is usable without deflection.

**Comment by julsemaan** [comment]
fixed by cca5b9f37f2dcb42aade67d2bc1a5d61ee63a74f
